server:
  port: 9094

spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  security:
    oauth2:
      resourceserver:
        url: http://localhost:8090
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.url}/oauth2/jwks

  resources:
    add-mappings: false